"""base unificada com categoria

Revision ID: 592a5ee3cac2
Revises: 
Create Date: 2026-03-29 15:47:14.856420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592a5ee3cac2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Noticia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('score_sentimento', sa.Float(), nullable=True),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.drop_table('noticia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticia',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), nullable=False),
    sa.Column('conteudo', sa.TEXT(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('data_publicacao', sa.DATETIME(), nullable=False),
    sa.Column('resumo', sa.TEXT(), nullable=True),
    sa.Column('score_sentimento', sa.FLOAT(), nullable=True),
    sa.Column('ativo_id', sa.INTEGER(), nullable=True),
    sa.Column('fonte', sa.VARCHAR(length=100), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.drop_table('Noticia')
    # ### end Alembic commands ###
